<?php
/** @var Worldline\PaymentCore\Block\Info $block */
$specificInfo = $block->getSpecificInformation();
$cardNumbers = $block->getPaymentInformation()->getCardLastNumbers();
?>
<?= $block->escapeHtml($block->getPaymentTitle()); ?>

<?php if ($cardNumbers): ?>
    <span><?= $block->escapeHtml(__('ending')) ?></span> <?= $block->escapeHtml($cardNumbers); ?>
<?php endif; ?>

<?php if ($block->getIconUrl()): ?>
    <img src="<?= $block->escapeUrl($block->getIconUrl()) ?>"
         style="max-height: <?= $block->escapeHtmlAttr($block->getMaxHeight()) ?>;
                aspect-ratio: <?= $block->escapeHtml($block->getAspectRatio()) ?>;"
         alt="<?= $block->escapeHtmlAttr($block->escapeHtml($block->getIconTitle())) ?>"
    >
<?php endif; ?>

<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $item): ?>
            <tr>
                <th><?= $block->escapeHtml($item['label']) ?>:</th>
                <td><?= $block->escapeHtml($item['value']) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>
