<?php
/**
 * @var Worldline\PaymentCore\Block\Adminhtml\System\Config\TestConnection $block
 * phpcs:disable Generic.Files.LineLength.TooLong
 */
?>
<td class="label">
    <label for="<?= $block->escapeHtml($block->getHtmlId()) ?>"></label>
</td>
<td class="value">
    <button class="scalable"
            type="button"
            id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"
            data-mage-init='{"checkConnection":{
        "url": "<?= $block->escapeUrl($block->getAjaxUrl()) ?>",
        "elementId": "<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>",
        "successText": "<?= $block->escapeHtmlAttr(__('Successful! Test again?')) ?>",
        "failedText": "<?= $block->escapeHtmlAttr(__('Connection failed! Test again?')) ?>",
        "fieldMapping": "<?= /* @noEscape */ $block->getFieldMapping() ?>"}, "validation": {}
    }'>
        <span id="<?= $block->escapeHtml($block->getHtmlId()) ?>_result"><?= $block->escapeHtml($block->getLabel()) ?></span>
    </button>
</td>
