<?php
/** @var Worldline\PaymentCore\Block\Sales\Creditmemo\Create\Surcharging $block */
$hasSurcharging = $block->hasSurcharging();
if (!$hasSurcharging) {
    return;
}
?>
<tr>
    <td class="label">
        <?= $block->escapeHtml(__('Surcharging')) ?>
        <div id="surcharging_amount_adv"></div>
    </td>
    <td>
        <input type="text"
               name="creditmemo[worldline_payment_surcharging]"
               value="<?= /* @noEscape */ $block->formatValue($block->getSurchargeAmount()) ?>"
               class="input-text admin__control-text not-negative-amount"
               id="worldline_payment_surcharging" />
    </td>
</tr>
